products:
  hangboard:
    build:
      main-pkg: cmd/hangboard
      os-archs:
      - os: linux
        arch: arm
      - os: linux
        arch: arm64
      - os: darwin
        arch: amd64
      version-var: version.version
